// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzN2rb0gWNSd5wUf-4TvLnC5AqR8cCvg',
    appId: '1:859080497045:web:2612da961befc592a4089c',
    messagingSenderId: '859080497045',
    projectId: 'task-app-d9ff4',
    authDomain: 'task-app-d9ff4.firebaseapp.com',
    storageBucket: 'task-app-d9ff4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGS3918Rp1uP0y4XNd9YBcwtj7fOyNTw',
    appId: '1:859080497045:android:331701ec8752f9f7a4089c',
    messagingSenderId: '859080497045',
    projectId: 'task-app-d9ff4',
    storageBucket: 'task-app-d9ff4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA65TJqJABBM9cEW_oLAfQJ7GzQd0F2d3s',
    appId: '1:859080497045:ios:58edb5b2d1c51e7ba4089c',
    messagingSenderId: '859080497045',
    projectId: 'task-app-d9ff4',
    storageBucket: 'task-app-d9ff4.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA65TJqJABBM9cEW_oLAfQJ7GzQd0F2d3s',
    appId: '1:859080497045:ios:b584d4a5ca23cc1fa4089c',
    messagingSenderId: '859080497045',
    projectId: 'task-app-d9ff4',
    storageBucket: 'task-app-d9ff4.appspot.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
