// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMLT4g2G_7nftmTDCwpO0qkGC5A0vektw',
    appId: '1:954973287112:web:f1fc9eaa9ea2dec52a6bfd',
    messagingSenderId: '954973287112',
    projectId: 'taskmanagment-ef2e5',
    authDomain: 'taskmanagment-ef2e5.firebaseapp.com',
    storageBucket: 'taskmanagment-ef2e5.appspot.com',
    measurementId: 'G-8SXZF756X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_3J68ni_yLAiFDo6p0GG3NQQgU3c8Q0',
    appId: '1:954973287112:android:5d5bfc78f9596bbe2a6bfd',
    messagingSenderId: '954973287112',
    projectId: 'taskmanagment-ef2e5',
    storageBucket: 'taskmanagment-ef2e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXYRYToQ-RQ6VeLvyajL_gy_9p5HXJVk',
    appId: '1:954973287112:ios:5100f8b967544cc42a6bfd',
    messagingSenderId: '954973287112',
    projectId: 'taskmanagment-ef2e5',
    storageBucket: 'taskmanagment-ef2e5.appspot.com',
    iosBundleId: 'com.example.taskMangement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXYRYToQ-RQ6VeLvyajL_gy_9p5HXJVk',
    appId: '1:954973287112:ios:5f8fbca2c611fad92a6bfd',
    messagingSenderId: '954973287112',
    projectId: 'taskmanagment-ef2e5',
    storageBucket: 'taskmanagment-ef2e5.appspot.com',
    iosBundleId: 'com.example.taskMangement.RunnerTests',
  );
}
